version: '2'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_DB=postgres
      - PGUSER=postgres
    env_file:
      - .env
  web:
    restart: unless-stopped
    build: .
    volumes:
      - ./share:/var/run/share
    env_file:
      - .env
    depends_on:
      - db
